package br.com.project.bookapi.entity;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "book")
public class Book {

	private String bookId;

	private Person author;

	private String title;

	private String publisher;

	private int year;

    public Book() {
	}

	public Book(Person author, String title, String publisher, int year) {
		this.author = author;
		this.title = title;
		this.publisher = publisher;
		this.year = year;
	}

	@Id
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	public String getBookId() {
		return bookId;
	}

    @DynamoDBAttribute(attributeName="author")
	public Person getAuthor() {
		return author;
	}

    @DynamoDBAttribute
	public String getTitle() {
		return title;
	}

    @DynamoDBAttribute
	public String getPublisher() {
		return publisher;
	}

    @DynamoDBAttribute
	public int getYear() {
		return year;
	}

	public void setBookId(String bookId) {
		this.bookId = bookId;
	}

	public void setAuthor(Person author) {
		this.author = author;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	public void setYear(int year) {
		this.year = year;
	}
}