package br.com.project.bookapi.entity;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "book")
public class Book {

	@Id
    @DynamoDBHashKey(attributeName = "bookId")
    @DynamoDBAutoGeneratedKey
    @JsonIgnore
	private String bookId;

    @DynamoDBAttribute
	private String title;
/*

    @DynamoDBAttribute
	private String author;

    @DynamoDBAttribute
	private String publisher;

    @DynamoDBAttribute
	private int year;*/

    /*
    public Book(String author, String title, String publisher, int year) {
		this.author = author;
		this.title = title;
		this.publisher = publisher;
		this.year = year;
	}*/
    
    public Book (String title) {
    	this.title = title;
    }
}
